export interface Gasto {
  id: string;
  codigo: string;
  label: string;
  documentos: string[];
  legislacao: string;
  obsJuridicas: string;
  obsEspecificas: string; // Plano Básico — bloqueado no Plano Livre
}

export interface Genero {
  id: string;
  label: string;
  icon: string;
  color: string;
  especies: Gasto[];
}

export const generos: Genero[] = [
  {
    id: 'contratacao-pessoal',
    label: 'Contratação de Pessoal',
    icon: 'group',
    color: 'teal',
    especies: [
      {
        id: 'despesas-pessoal',
        codigo: '2.1',
        label: 'Salários e gratificações',
        documentos: [
          'Folha de pagamento assinada pelo funcionário',
          'Contracheque ou recibo de pagamento',
          'Contrato de trabalho assinado (CLT ou por prazo determinado)',
          'Comprovante de transferência bancária ou recibo de pagamento em espécie',
        ],
        legislacao: 'Art. 22 da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Todo pagamento a funcionário de campanha deve ser declarado no SPCE. O pagamento informal configura irregularidade e pode levar à desaprovação das contas.',
        obsEspecificas: 'O valor pago não pode exceder o teto salarial de referência de mercado para a função. Gratificações devem ter motivação documentada. Atenção ao limite de gastos com pessoal fixado na resolução do TSE para cada cargo.',
      },
      {
        id: 'encargos-sociais',
        codigo: '2.2',
        label: 'Encargos sociais',
        documentos: [
          'Guia GPS (INSS patronal) com comprovante de pagamento',
          'GFIP ou eSocial — guia de recolhimento do FGTS',
          'Extrato do FGTS do trabalhador',
          'DAE (Documento de Arrecadação do eSocial) quando aplicável',
        ],
        legislacao: 'CLT, arts. 7º e 8º — Lei 8.036/1990 (FGTS) — Res.-TSE 23.731/2024',
        obsJuridicas: 'O não recolhimento dos encargos trabalhistas gera irregularidade formal nas contas. O TSE pode exigir comprovação do recolhimento como condição para aprovação.',
        obsEspecificas: 'Campanhas com mais de 5 funcionários devem manter cadastro atualizado no eSocial. Parcelamentos de débitos previdenciários devem ser informados na prestação de contas com o número do acordo.',
      },
      {
        id: 'militancia-mobilizacao',
        codigo: '2.34',
        label: 'Militância e mobilização de rua',
        documentos: [
          'Nota fiscal da gráfica/confecção (uniformes, camisetas, bonés)',
          'Recibo de material distribuído (panfletos, brindes)',
          'Lista de presença dos voluntários, quando houver remuneração',
          'Contrato de serviço de coordenação de atividades (se terceirizado)',
        ],
        legislacao: 'Art. 36 da Lei 9.504/1997 — Res.-TSE 23.731/2024, arts. 18 e 43',
        obsJuridicas: 'Voluntários não remunerados não precisam ser declarados na folha de pessoal. A partir do momento em que há qualquer contraprestação (dinheiro, alimentação, transporte), configura-se vínculo remuneratório e deve ser declarado.',
        obsEspecificas: 'É vedado o recrutamento de militantes com promessa de cargo ou benefício futuro. A distribuição de camisetas e uniformes identificados com o candidato é permitida, mas a distribuição de bens de valor (cestas, brindes caros) pode configurar captação ilícita.',
      },
      {
        id: 'reembolsos-eleitores',
        codigo: '2.35',
        label: 'Reembolsos a eleitores',
        documentos: [
          'Comprovantes originais de cada despesa realizada pelo eleitor',
          'Recibo de reembolso assinado pelo eleitor com CPF',
          'Declaração do eleitor descrevendo a finalidade do gasto',
          'Comprovante de transferência bancária ou pagamento do reembolso',
        ],
        legislacao: 'Art. 22, §2º da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'O reembolso só é válido se o gasto realizado pelo eleitor se enquadrar em categoria permitida pela legislação eleitoral. Reembolsos sem comprovação documental são tratados como despesas irregulares.',
        obsEspecificas: 'Eleitores que realizarem gastos habituais e repetidos em nome da campanha podem ser enquadrados como funcionários informais, gerando risco de reconhecimento de vínculo empregatício. Limite recomendado: reembolsos pontuais e devidamente justificados.',
      },
    ],
  },
  {
    id: 'materiais-impressos-carro-som',
    label: 'Materiais Impressos e Carro de Som',
    icon: 'print',
    color: 'violet',
    especies: [
      {
        id: 'publicidade-carros-som',
        codigo: '2.7',
        label: 'Contratação de carro de som',
        documentos: [
          'Nota fiscal do serviço emitida pela empresa (CNPJ ativo)',
          'Contrato de prestação de serviços com datas e roteiros',
          'Registro dos horários e locais de circulação',
          'Autorização municipal (quando exigida pelo município)',
        ],
        legislacao: 'Art. 37, §2º da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'A circulação de carro de som é restrita a horários e áreas definidos pela legislação municipal. O descumprimento pode gerar multa eleitoral e impugnação de despesa.',
        obsEspecificas: 'Em municípios com legislação restritiva, verifique o alvará de circulação de som. Carro de som em propriedades privadas (com autorização) tem regras distintas do espaço público. Proibido em perímetro de 200m de escola em dia de eleição.',
      },
      {
        id: 'publicidade-adesivos-santinhos',
        codigo: '2.15',
        label: 'Adesivos e santinhos',
        documentos: [
          'Nota fiscal da gráfica com CNPJ ativo',
          'NF deve discriminar: quantidade, tamanho, tipo e valor unitário',
          'Amostra física dos materiais produzidos arquivada junto à NF',
          'Registro de distribuição (local, data e responsável)',
        ],
        legislacao: 'Art. 38 da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Todo material impresso deve conter: número de registro do candidato, sigla do partido, CNPJ do responsável financeiro e número do CNPJ da gráfica. A ausência de qualquer desses elementos pode levar à apreensão do material.',
        obsEspecificas: 'É vedada a fixação de adesivos em bens públicos, postes, árvores e viadutos. Multa por colagem irregular pode ser lançada como despesa, mas gera histórico negativo na prestação. Santinhos distribuídos em dia de eleição configuram infração.',
      },
      {
        id: 'publicidade-materiais-impressos',
        codigo: '2.12',
        label: 'Outros materiais impressos',
        documentos: [
          'Nota fiscal da gráfica (CNPJ ativo) com descrição detalhada',
          'Amostra física do material produzido',
          'Comprovante de pagamento',
          'Arte final aprovada (arquivo digital ou impresso)',
        ],
        legislacao: 'Art. 38 da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Banners, faixas e placas em locais públicos dependem de autorização específica e têm limitações de tamanho definidas pela Justiça Eleitoral. Verifique as regras do TRE local antes da instalação.',
        obsEspecificas: 'Outdoors e painéis eletrônicos têm regras distintas dos materiais impressos comuns e podem configurar categoria separada de despesa. Consulte a resolução vigente para o enquadramento correto.',
      },
      {
        id: 'jingles-vinhetas',
        codigo: '2.31',
        label: 'Produção de jingle',
        documentos: [
          'Nota fiscal da produtora musical (CNPJ ativo)',
          'Contrato de prestação de serviços com escopo detalhado',
          'Termo de cessão de direitos autorais assinado',
          'Arquivos finais entregues (MP3, WAV) como prova do produto',
        ],
        legislacao: 'Art. 38 da Lei 9.504/1997 — Lei 9.610/1998 (Direitos Autorais) — Res.-TSE 23.731/2024',
        obsJuridicas: 'A cessão de direitos autorais deve ser expressa e por escrito. Sem ela, o uso do jingle pode ser questionado mesmo após o pagamento. Músicas de terceiros (covers, adaptações) exigem autorização adicional do autor original.',
        obsEspecificas: 'Jingles usados em rádio e TV têm enquadramento distinto dos usados em carros de som ou redes sociais. Cada meio de veiculação pode gerar uma nota fiscal separada. Verifique se a produtora também é responsável pela distribuição ou se isso é contratado separadamente.',
      },
      {
        id: 'correspondencias-postais',
        codigo: '2.9',
        label: 'Correspondências postais',
        documentos: [
          'Comprovante de postagem dos Correios ou serviço equivalente',
          'Aviso de recebimento (AR), quando disponível',
          'Lista de destinatários (quando exigida pelo TSE)',
          'Amostra do material enviado',
        ],
        legislacao: 'Art. 36, §2º da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Envio em massa de correspondências eleitorais deve respeitar os limites de propaganda definidos no calendário eleitoral. O envio antes do período permitido configura propaganda antecipada.',
        obsEspecificas: 'Mala direta enviada para listas adquiridas de terceiros pode gerar questionamento sobre a origem do cadastro eleitoral. Recomenda-se usar apenas listas próprias e documentar a origem dos dados.',
      },
    ],
  },
  {
    id: 'radio-tv-audiovisual',
    label: 'Rádio, TV, Audiovisual, Jornais e Revistas',
    icon: 'play_circle',
    color: 'indigo',
    especies: [
      {
        id: 'producao-radio-tv',
        codigo: '2.23',
        label: 'Produção de programas de rádio/TV',
        documentos: [
          'Nota fiscal da produtora com CNPJ ativo',
          'Contrato de produção com escopo e prazo detalhados',
          'Arquivos finais (vídeo/áudio) entregues como prova',
          'Comprovante de exibição ou transmissão do programa',
        ],
        legislacao: 'Arts. 44–47 da Lei 9.504/1997 (HGPE) — Res.-TSE 23.731/2024',
        obsJuridicas: 'Programas veiculados no Horário Gratuito de Propaganda Eleitoral (HGPE) seguem regras rígidas de conteúdo e tempo definidas pelo TSE. Produções fora do HGPE exigem identificação clara como propaganda paga.',
        obsEspecificas: 'O uso de imagens de candidatos concorrentes sem autorização, mesmo em contexto crítico, pode configurar propaganda negativa vedada. Verifique previamente com o advogado eleitoral o conteúdo de cada peça antes da veiculação.',
      },
      {
        id: 'material-audiovisual',
        codigo: '2.40',
        label: 'Produção audiovisual',
        documentos: [
          'Nota fiscal da produtora ou agência (CNPJ ativo)',
          'Contrato com descrição detalhada dos serviços',
          'Arquivos digitais finais (vídeos, fotos, artes)',
          'Relatório de entrega ou aceite formal do cliente',
        ],
        legislacao: 'Art. 57-A da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Materiais audiovisuais veiculados em redes sociais devem identificar claramente o responsável pela publicação (candidato ou partido). A ausência de identificação pode gerar multa e ordem de remoção.',
        obsEspecificas: 'Vídeos impulsionados pagos têm enquadramento distinto da produção audiovisual — o impulsionamento é lançado em categoria própria (2.38). Evite registrar o custo de produção e o de veiculação na mesma nota fiscal.',
      },
      {
        id: 'publicidade-jornais-revistas',
        codigo: '2.14',
        label: 'Jornais e revistas',
        documentos: [
          'Nota fiscal do veículo de comunicação (CNPJ ativo)',
          'Exemplar do jornal ou revista com o anúncio publicado',
          'Contrato de veiculação ou ordem de publicação',
          'Comprovante de pagamento',
        ],
        legislacao: 'Art. 36, §4º e art. 43 da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'Anúncios pagos em veículos impressos devem ser identificados como propaganda eleitoral paga. A simulação de matéria jornalística como propaganda (publi-editorial) é vedada.',
        obsEspecificas: 'Veículos de pequena circulação local podem ter enquadramento fiscal diferenciado. Verifique se o veículo está regularmente registrado como empresa de comunicação antes de contratar.',
      },
      {
        id: 'vinhetas-slogans',
        codigo: '2.31',
        label: 'Jingles e vinhetas',
        documentos: [
          'Nota fiscal da produtora (CNPJ ativo)',
          'Termo de cessão de direitos autorais',
          'Arquivos finais de áudio (MP3, WAV)',
          'Contrato com especificação dos meios de veiculação autorizados',
        ],
        legislacao: 'Lei 9.610/1998 (Direitos Autorais) — Res.-TSE 23.731/2024',
        obsJuridicas: 'Cada contrato de produção de jingle deve especificar os meios de veiculação autorizados. Uma vinheta produzida para rádio não pode ser usada em TV ou internet sem nova autorização contratual.',
        obsEspecificas: 'Se o mesmo jingle for usado em rádio, carros de som e redes sociais, considere contratar os direitos de uso por mídia individualmente para facilitar o rastreamento na prestação de contas.',
      },
      {
        id: 'servicos-proprios-terceiros',
        codigo: '2.29',
        label: 'Serviços próprios por terceiros',
        documentos: [
          'Contrato de prestação de serviços com escopo detalhado',
          'Nota fiscal com discriminação dos serviços executados',
          'Relatório de entrega ou cronograma de execução',
          'Comprovante de regularidade do prestador (CNPJ ativo, certidões)',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Agências de publicidade que prestam serviços integrados (criação, produção e veiculação) devem detalhar cada etapa na nota fiscal. O TSE pode questionar notas genéricas sem discriminação dos serviços.',
        obsEspecificas: 'Verifique se a agência está habilitada a prestar serviços eleitorais (sem impedimentos junto à Justiça Eleitoral). Contratos com agências ligadas a candidatos concorrentes podem gerar conflito de interesse.',
      },
    ],
  },
  {
    id: 'propaganda-internet',
    label: 'Propaganda na Internet',
    icon: 'language',
    color: 'sky',
    especies: [
      {
        id: 'impulsionamento-conteudos',
        codigo: '2.38',
        label: 'Impulsionamento de conteúdo',
        documentos: [
          'Comprovante de pagamento da plataforma (recibo ou extrato)',
          'Relatório de desempenho do anúncio (impressões, alcance)',
          'Print ou cópia do anúncio veiculado com identificação do responsável',
          'Extrato de cada campanha paga com plataforma, período e valor',
        ],
        legislacao: 'Art. 57-C e 57-D da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Somente plataformas digitais com representação legal no Brasil podem receber pagamento por impulsionamento eleitoral. O uso de plataformas não habilitadas pelo TSE pode configurar captação ilícita de recursos.',
        obsEspecificas: 'Cada anúncio pago deve conter identificação clara do responsável (candidato ou partido) e número de registro. Anúncios direcionados a menores de 16 anos são vedados. Plataformas devem emitir relatório de transparência conforme exigido pelo TSE.',
      },
      {
        id: 'paginas-internet',
        codigo: '2.26',
        label: 'Criação e manutenção de sites',
        documentos: [
          'Nota fiscal da empresa desenvolvedora (CNPJ ativo)',
          'Contrato de desenvolvimento e/ou manutenção',
          'Comprovante de registro do domínio (recibo do registrador)',
          'Print ou URL do site publicado como prova',
        ],
        legislacao: 'Art. 57-A da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'Sites de campanha devem conter identificação do responsável, CNPJ do responsável financeiro e número de registro do candidato. Sites criados antes do período de campanha podem configurar propaganda antecipada.',
        obsEspecificas: 'Domínios registrados em nome pessoal do candidato, e não do comitê, podem gerar questionamento na auditoria. Prefira registrar o domínio em nome do comitê financeiro. Hospedagem paga deve ser lançada separadamente da criação.',
      },
      {
        id: 'redes-sociais',
        codigo: '2.41',
        label: 'Redes sociais e outros',
        documentos: [
          'Nota fiscal da agência ou profissional de social media (CNPJ ativo)',
          'Contrato com escopo de serviços (criação de conteúdo, gestão)',
          'Relatório mensal de atividades realizadas',
          'Prints das publicações realizadas durante a campanha',
        ],
        legislacao: 'Art. 57-A da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'A gestão de redes sociais por terceiros remunerados deve ser declarada como despesa eleitoral. Perfis criados antes do período de campanha podem ser usados, mas publicações com teor eleitoral antes do período permitido configuram propaganda antecipada.',
        obsEspecificas: 'Publicações patrocinadas em redes sociais devem ser lançadas em 2.38 (Impulsionamento), não nesta categoria. Esta categoria cobre apenas a produção orgânica de conteúdo e gestão das contas.',
      },
      {
        id: 'taxa-financiamento-coletivo',
        codigo: '2.37',
        label: 'Taxa de financiamento coletivo',
        documentos: [
          'Extrato da plataforma com valor arrecadado e taxas descontadas',
          'Comprovante de habilitação da plataforma junto ao TSE',
          'Relatório de doadores (nome, CPF e valor)',
          'Comprovante de transferência do valor líquido para a conta da campanha',
        ],
        legislacao: 'Art. 22-A da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'Apenas plataformas previamente habilitadas pelo TSE podem operar financiamento coletivo eleitoral. A taxa cobrada pela plataforma é lançada como despesa, e o valor bruto arrecadado como receita.',
        obsEspecificas: 'Doações via financiamento coletivo têm os mesmos limites das doações diretas (até 10% dos rendimentos brutos do doador no ano anterior). O candidato é responsável por verificar a conformidade de cada doação recebida.',
      },
    ],
  },
  {
    id: 'imoveis-comite',
    label: 'Imóveis e Comitê de Campanha',
    icon: 'home_work',
    color: 'amber',
    especies: [
      {
        id: 'locacao-bens-imoveis',
        codigo: '2.4',
        label: 'Locação do comitê',
        documentos: [
          'Contrato de locação com CNPJ ou CPF do locador',
          'Nota fiscal ou recibo do aluguel (CNPJ do locador ativo)',
          'Comprovante de pagamento mensal',
          'Laudo de avaliação de mercado (se o valor for acima da média regional)',
        ],
        legislacao: 'Art. 22 da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Cessão gratuita de imóvel deve ser declarada pelo valor de mercado como doação, com laudo ou pesquisa de preço de referência. O locador não pode ser empresa com contrato com o poder público.',
        obsEspecificas: 'Aluguel de imóvel de parente do candidato é permitido, mas sujeito a escrutínio rigoroso quanto ao preço. Sublocação sem autorização expressa do proprietário invalida o contrato e a despesa. O imóvel deve ser usado exclusivamente para fins de campanha.',
      },
      {
        id: 'agua',
        codigo: '2.17',
        label: 'Água',
        documentos: [
          'Fatura da concessionária de água (com código de barras)',
          'Comprovante de pagamento',
          'Declaração de uso exclusivo para campanha (se aplicável)',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Se o imóvel for compartilhado com uso não eleitoral, declare apenas a parte proporcional ao período e uso da campanha. Rateios devem ser documentados com critério claro.',
        obsEspecificas: 'Em imóveis cedidos gratuitamente, as contas de consumo (água, luz) pagas pelo candidato são despesas eleitorais declaráveis, mas a cessão em si deve ser declarada como doação pelo valor de mercado.',
      },
      {
        id: 'energia-eletrica',
        codigo: '2.18',
        label: 'Energia elétrica',
        documentos: [
          'Fatura da concessionária de energia (com código de barras)',
          'Comprovante de pagamento',
          'Declaração proporcional de uso (se o imóvel tiver uso misto)',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'O rateio proporcional deve ser documentado. A concessionária pode ser solicitada a emitir histórico de consumo para subsidiar o cálculo do período eleitoral.',
        obsEspecificas: 'Geradores de energia utilizados em eventos são lançados em categoria própria (2.44). Esta categoria cobre apenas o consumo ordinário de energia do comitê.',
      },
      {
        id: 'telefone-internet',
        codigo: '2.30',
        label: 'Telefone e internet',
        documentos: [
          'Fatura da operadora com discriminação de ligações',
          'Comprovante de pagamento',
          'Declaração de uso proporcional (se linha pessoal)',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Linhas de uso misto (pessoal e eleitoral) devem ter a proporção de uso eleitoral estimada e documentada. Recomenda-se contratar linha exclusiva para a campanha para facilitar a comprovação.',
        obsEspecificas: 'Chips e planos contratados exclusivamente para a campanha devem estar em nome do comitê. Planos pessoais rateados são aceitos, mas aumentam o risco de questionamento na auditoria.',
      },
      {
        id: 'pre-instalacao-comite',
        codigo: '2.32',
        label: 'Obras e pré-instalação',
        documentos: [
          'Nota fiscal dos materiais de construção (CNPJ ativo)',
          'Nota fiscal ou recibo da mão de obra',
          'Autorização expressa do proprietário do imóvel para a obra',
          'Fotos do antes e depois da reforma',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Obras em imóvel alugado sem autorização do proprietário podem gerar questionamento da despesa. O valor da benfeitoria incorporada ao imóvel pode ser considerado doação ao proprietário se não houver previsão de indenização.',
        obsEspecificas: 'Reformas de grande porte em imóvel alugado por curto período de campanha podem ser questionadas quanto à proporcionalidade. O TSE pode avaliar se o valor da obra é compatível com o período de uso.',
      },
      {
        id: 'locacao-bens-moveis',
        codigo: '2.8',
        label: 'Locação de bens móveis',
        documentos: [
          'Contrato de locação com descrição dos itens, período e valor',
          'Nota fiscal do serviço de locação (CNPJ ativo)',
          'Comprovante de devolução dos bens ao final do contrato',
          'Comprovante de pagamento',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'A locação deve ser de pessoa jurídica regularmente constituída. Locações informais de pessoa física sem registro são vedadas. O valor deve ser compatível com o mercado.',
        obsEspecificas: 'Equipamentos de som e iluminação para eventos podem ser lançados aqui ou em categoria de eventos (2.19/2.21). Use o critério de uso predominante para definir o enquadramento.',
      },
      {
        id: 'materiais-expediente',
        codigo: '2.10',
        label: 'Materiais de expediente',
        documentos: [
          'Nota fiscal do fornecedor com discriminação dos itens',
          'Comprovante de pagamento',
          'Lista de itens adquiridos (para compras de grande volume)',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Compras mistas (materiais de campanha e pessoais na mesma NF) devem ser evitadas. Caso ocorram, apenas a parte da campanha deve ser lançada, com destaque na documentação.',
        obsEspecificas: 'Materiais de expediente de alto valor (computadores, impressoras) devem ser lançados como aquisição de bens (2.28). Esta categoria cobre consumíveis e materiais de uso rotineiro.',
      },
      {
        id: 'geradores-energia',
        codigo: '2.44',
        label: 'Geradores de energia',
        documentos: [
          'Contrato de locação com especificação do equipamento e período',
          'Nota fiscal do fornecedor (CNPJ ativo)',
          'Comprovante de pagamento',
          'Registro do evento ou uso para o qual o gerador foi utilizado',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Geradores locados para comícios e eventos devem ter sua despesa vinculada ao evento correspondente na prestação de contas. Isso facilita a conferência e reduz o risco de questionamento.',
        obsEspecificas: 'Aquisição de gerador (e não locação) é lançada em 2.28 (Aquisição de bens). O gerador adquirido com recursos de campanha deve ser destinado conforme legislação ao final do pleito.',
      },
    ],
  },
  {
    id: 'carros-veiculos',
    label: 'Carros e Outros Veículos',
    icon: 'directions_car',
    color: 'orange',
    especies: [
      {
        id: 'cessao-locacao-veiculos',
        codigo: '2.33',
        label: 'Locação de veículos',
        documentos: [
          'Contrato de locação com placa, modelo, período e valor',
          'CRLV do veículo (documento do veículo)',
          'Nota fiscal da locadora (CNPJ ativo)',
          'Comprovante de pagamento e devolução do veículo',
        ],
        legislacao: 'Art. 22 da Lei 9.504/1997 — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Veículos de campanha não podem transportar eleitores para a seção eleitoral no dia da votação, sob pena de configurar captação ilícita de sufrágio. A vedação se aplica inclusive a condutor voluntário.',
        obsEspecificas: 'Locação de veículos de luxo pode ser questionada quanto à proporcionalidade em relação ao cargo pleiteado. O TSE avalia a compatibilidade do gasto com o porte da campanha.',
      },
      {
        id: 'combustiveis-lubrificantes',
        codigo: '2.11',
        label: 'Combustíveis e lubrificantes',
        documentos: [
          'Nota fiscal ou cupom fiscal do posto (com CNPJ)',
          'Registro da placa do veículo abastecido',
          'Data e quantidade (litros) do abastecimento',
          'Declaração de cessão do veículo (se for de terceiro)',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Veículos particulares usados na campanha devem ter declaração formal de cessão do proprietário, mesmo que seja do próprio candidato. Sem isso, o combustível pode ser questionado como despesa pessoal.',
        obsEspecificas: 'Controle de quilometragem por veículo é recomendado para demonstrar o uso efetivamente eleitoral. Abastecimentos em locais distantes da região de campanha sem justificativa podem gerar questionamento.',
      },
      {
        id: 'cessao-veiculos',
        codigo: '2.33',
        label: 'Cessão de veículos',
        documentos: [
          'Termo de cessão gratuita com identificação do proprietário e veículo (placa)',
          'CRLV do veículo cedido',
          'Declaração do período de cessão',
          'Avaliação do valor de mercado da diária (para declarar como doação)',
        ],
        legislacao: 'Art. 23, §1º da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'A cessão gratuita de veículo é declarada como doação pelo valor de mercado da diária de locação. O cedente deve ser pessoa física sem vedação legal para doação eleitoral.',
        obsEspecificas: 'Cessão de veículo por empresa é tratada como doação de pessoa jurídica, vedada pela legislação eleitoral. Apenas pessoa física pode ceder veículo gratuitamente para a campanha.',
      },
    ],
  },
  {
    id: 'viagens-hospedagem',
    label: 'Viagens e Hospedagem',
    icon: 'flight',
    color: 'cyan',
    especies: [
      {
        id: 'passagem-aerea',
        codigo: '2.6',
        label: 'Passagens aéreas',
        documentos: [
          'Nota fiscal ou recibo da agência/companhia aérea',
          'Bilhete eletrônico (e-ticket) com trecho e data',
          'Comprovante de embarque (boarding pass)',
          'Justificativa da finalidade eleitoral do deslocamento',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Passagens adquiridas com pontos de programas de fidelidade devem ser declaradas pelo valor de mercado como doação do programa ou do candidato. O TSE considera o benefício econômico, não apenas o desembolso financeiro.',
        obsEspecificas: 'Trechos fora da circunscrição eleitoral do candidato podem ser questionados quanto à finalidade eleitoral. Documente sempre a agenda política que justificou o deslocamento.',
      },
      {
        id: 'hospedagem',
        codigo: '2.36',
        label: 'Hospedagem',
        documentos: [
          'Nota fiscal do estabelecimento de hospedagem (CNPJ ativo)',
          'Comprovante de check-in e check-out',
          'Identificação dos hóspedes (equipe de campanha)',
          'Comprovante de pagamento',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Hospedagem de eleitores custeada pela campanha pode ser interpretada como captação ilícita de sufrágio, especialmente próxima ao dia da eleição. Limite a hospedagem a membros da equipe de campanha.',
        obsEspecificas: 'Hotéis de luxo ou diárias acima da média de mercado para a região podem ser questionados quanto à proporcionalidade. O TSE analisa o custo-benefício das despesas no contexto do cargo pleiteado.',
      },
      {
        id: 'transporte-deslocamento',
        codigo: '2.5',
        label: 'Transporte e deslocamento',
        documentos: [
          'Recibo ou nota fiscal do serviço de transporte',
          'Comprovante de viagem (aplicativo: exportar PDF do extrato)',
          'Para fretamento: contrato e nota fiscal da empresa',
          'Declaração de finalidade eleitoral do deslocamento',
        ],
        legislacao: 'Art. 302 do Código Eleitoral — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'O transporte de eleitores para qualquer evento de campanha é vedado se caracterizar captação de sufrágio. Transporte da equipe de trabalho é permitido. A distinção entre equipe e eleitores deve ser clara e documentada.',
        obsEspecificas: 'Fretamento de ônibus para comícios ou eventos de campanha é permitido para a equipe, mas o transporte de público em geral caracteriza conduta vedada. Mantenha lista nominal dos transportados em cada fretamento.',
      },
    ],
  },
  {
    id: 'servicos-juridicos-contabeis',
    label: 'Serviços Jurídicos e Contábeis',
    icon: 'gavel',
    color: 'rose',
    especies: [
      {
        id: 'servicos-contabeis',
        codigo: '2.43',
        label: 'Contratação de contador',
        documentos: [
          'Contrato de prestação de serviços contábeis assinado',
          'Nota fiscal ou recibo dos serviços prestados',
          'Registro no CRC do profissional ou empresa',
          'Comprovante de pagamento dos honorários',
        ],
        legislacao: 'Art. 22, §2º da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'O responsável pela prestação de contas deve ser contador registrado no CRC. A responsabilidade técnica pelo SPCE recai sobre o contador — mantenha o contrato atualizado durante todo o período eleitoral.',
        obsEspecificas: 'Contadores que prestam serviços a múltiplos candidatos concorrentes no mesmo pleito podem ter impedimento ético. Verifique com o CRC regional as normas aplicáveis. O contrato deve prever responsabilidade técnica específica pela prestação de contas eleitoral.',
      },
      {
        id: 'servicos-advocaticios',
        codigo: '2.42',
        label: 'Contratação de advogado',
        documentos: [
          'Contrato de prestação de serviços advocatícios',
          'Nota fiscal (pessoa jurídica) ou recibo com retenção de ISS/IR (pessoa física)',
          'Número de inscrição na OAB',
          'Comprovante de pagamento dos honorários',
        ],
        legislacao: 'Art. 22 da Lei 9.504/1997 — Estatuto da OAB — Res.-TSE 23.731/2024',
        obsJuridicas: 'Honorários advocatícios pagos fora do período da campanha, mas relacionados a ela, podem ser incluídos na prestação de contas se devidamente documentados. Honorários de êxito devem ser declarados quando do pagamento efetivo.',
        obsEspecificas: 'Advogados que atuam simultaneamente para candidatos adversários no mesmo pleito podem ter conflito de interesse disciplinar pela OAB. Verifique o histórico profissional antes da contratação.',
      },
      {
        id: 'pesquisas-testes',
        codigo: '2.20',
        label: 'Pesquisas eleitorais',
        documentos: [
          'Contrato com empresa de pesquisa registrada no TSE',
          'Metodologia da pesquisa',
          'Relatório completo dos resultados',
          'Nota fiscal dos serviços (CNPJ ativo)',
        ],
        legislacao: 'Arts. 33–35 da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'Pesquisas divulgadas publicamente devem ser registradas no TRE/TSE antes da divulgação, com identificação da contratante, metodologia e margem de erro. A divulgação sem registro é infração eleitoral.',
        obsEspecificas: 'Pesquisas contratadas para uso interno (não divulgadas) não precisam ser registradas, mas devem ser lançadas como despesa. Mantenha o relatório confidencial em arquivo separado para eventual diligência da Justiça Eleitoral.',
      },
      {
        id: 'servicos-terceiros',
        codigo: '2.13',
        label: 'Outros serviços de terceiros',
        documentos: [
          'Contrato de prestação de serviços com escopo definido',
          'Nota fiscal com descrição clara do serviço (CNPJ ativo)',
          'Relatório de entrega ou conclusão dos serviços',
          'Comprovante de pagamento',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Serviços prestados por empresas com sócios que sejam cônjuge, companheiro ou parente do candidato até o 3º grau podem ser questionados. Verifique o quadro societário antes de contratar.',
        obsEspecificas: 'Para serviços recorrentes (mensais), emita um contrato global e notas fiscais mensais individuais. Evite contratos abertos sem escopo definido — o TSE pode questionar a finalidade eleitoral.',
      },
    ],
  },
  {
    id: 'despesas-obrigatorias',
    label: 'Despesas Obrigatórias',
    icon: 'account_balance',
    color: 'slate',
    especies: [
      {
        id: 'encargos-sociais-obrig',
        codigo: '2.2',
        label: 'Contribuições sociais',
        documentos: [
          'GPS (Guia da Previdência Social) com comprovante de pagamento',
          'Guia FGTS com comprovante de recolhimento',
          'eSocial: DAE com comprovante de pagamento',
          'GFIP (Guia de Recolhimento do FGTS e Informações à Previdência)',
        ],
        legislacao: 'Lei 8.212/1991 — Lei 8.036/1990 — Res.-TSE 23.731/2024',
        obsJuridicas: 'O não recolhimento de contribuições previdenciárias é irregularidade formal que pode fundamentar a desaprovação das contas. O TSE verifica o recolhimento cruzando com os dados da folha de pagamento declarada.',
        obsEspecificas: 'Campanhas com trabalhadores contratados via MEI (Microempreendedor Individual) têm dinâmica de recolhimento diferente. O MEI recolhe por conta própria e não gera obrigações patronais para o contratante, mas exige NF dos serviços prestados.',
      },
      {
        id: 'impostos-contribuicoes',
        codigo: '2.3',
        label: 'Impostos',
        documentos: [
          'DARF com comprovante de pagamento (IR retido na fonte)',
          'DAM com comprovante de pagamento (ISS municipal)',
          'Extrato da conta da campanha demonstrando retenção',
          'Nota fiscal do serviço que originou o imposto',
        ],
        legislacao: 'Lei 5.172/1966 (CTN) — Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Os impostos retidos na fonte devem ser recolhidos dentro do prazo legal, mesmo que o pagamento ao prestador seja parcelado. O atraso gera multa e juros que também devem ser declarados.',
        obsEspecificas: 'ISS retido sobre serviços prestados por profissionais autônomos deve ser recolhido ao município onde o serviço foi prestado, não necessariamente onde o candidato tem domicílio eleitoral.',
      },
      {
        id: 'taxas',
        codigo: '2.3',
        label: 'Taxas',
        documentos: [
          'DAM ou guia de recolhimento com comprovante de pagamento',
          'Documento que originou a taxa (alvará, certidão, autorização)',
          'Comprovante de pagamento',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Taxas pagas à Justiça Eleitoral (multas, emolumentos) são despesas eleitorais obrigatórias. Taxas municipais para eventos (alvarás de comício) também são declaráveis nesta categoria.',
        obsEspecificas: 'Taxas de cartório para reconhecimento de firma e autenticação de documentos da campanha são declaráveis. Guarde todos os recibos de taxas pagas durante o período eleitoral, mesmo os de baixo valor.',
      },
      {
        id: 'encargos-financeiros',
        codigo: '2.22',
        label: 'Tarifas bancárias e encargos',
        documentos: [
          'Extrato bancário da conta da campanha com tarifas destacadas',
          'Fatura de cartão corporativo (se houver) com encargos',
          'Contrato de crédito ou financiamento (se houver)',
          'Comprovante de pagamento dos encargos',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'Operações de crédito contratadas para financiar a campanha devem ser declaradas como receita no momento da contratação e como despesa no pagamento. Os juros e encargos são lançados nesta categoria.',
        obsEspecificas: 'Tarifas bancárias da conta da campanha são automaticamente evidenciadas no extrato bancário entregue à Justiça Eleitoral pelas instituições financeiras. Certifique-se de que os lançamentos no SPCE correspondem ao extrato oficial.',
      },
      {
        id: 'multas-eleitorais',
        codigo: '2.24',
        label: 'Multas eleitorais',
        documentos: [
          'Notificação ou auto de infração que originou a multa',
          'DARF ou guia de pagamento com comprovante de quitação',
          'Decisão judicial ou administrativa que impôs a multa',
          'Comprovante de pagamento dentro do prazo',
        ],
        legislacao: 'Arts. 36–41 da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'Multas pagas fora do prazo geram acréscimos de juros e correção que também devem ser declarados. Multas impugnadas judicialmente devem ser declaradas quando do pagamento definitivo, não da imposição.',
        obsEspecificas: 'Multas por propaganda irregular (adesivos em bem público, propaganda antecipada) são declaráveis como despesa, mas sinalizam irregularidade histórica que pode pesar na avaliação das contas pelo juiz eleitoral.',
      },
      {
        id: 'doacoes-candidatos-partidos',
        codigo: '2.25',
        label: 'Doações a candidatos/partidos',
        documentos: [
          'Recibo de doação emitido pelo beneficiário',
          'Comprovante de transferência bancária',
          'Registro simultâneo como receita no SPCE do beneficiário',
          'Verificação do registro do beneficiário na Justiça Eleitoral',
        ],
        legislacao: 'Art. 23, §3º da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'A doação entre candidatos deve respeitar os limites legais de arrecadação do beneficiário. O doador responde solidariamente se a doação ultrapassar o limite e o beneficiário não estornar o excesso.',
        obsEspecificas: 'Doações entre candidatos do mesmo partido para equilibrar recursos em campanhas proporcionais são práticas comuns, mas devem ser documentadas rigorosamente. O TSE cruza as informações de ambos os candidatos no SPCE.',
      },
      {
        id: 'aquisicao-bens',
        codigo: '2.28',
        label: 'Aquisição de bens',
        documentos: [
          'Nota fiscal de venda com CNPJ do vendedor e descrição do bem',
          'Comprovante de pagamento',
          'Inventário dos bens adquiridos com a campanha',
          'Termo de destinação dos bens ao final do pleito',
        ],
        legislacao: 'Art. 22, §9º da Lei 9.504/1997 — Res.-TSE 23.731/2024',
        obsJuridicas: 'Bens adquiridos com recursos de campanha não pertencem ao candidato — devem ser destinados ao partido, doados ou leiloados conforme a legislação ao final do pleito. A retenção indevida dos bens pode fundamentar desaprovação das contas.',
        obsEspecificas: 'Bens de valor acima de R$ 5.000,00 podem exigir licitação interna ou justificativa de contratação direta, dependendo das normas internas do partido. Consulte o estatuto partidário antes da aquisição.',
      },
      {
        id: 'diversas-especificar',
        codigo: '2.27',
        label: 'Diversas a especificar',
        documentos: [
          'Nota fiscal ou recibo com CNPJ ativo do fornecedor',
          'Descrição detalhada da despesa no campo do SPCE',
          'Justificativa da finalidade eleitoral',
          'Comprovante de pagamento',
        ],
        legislacao: 'Res.-TSE 23.731/2024, art. 43',
        obsJuridicas: 'O uso excessivo desta categoria genérica pode gerar questionamento na análise técnica das contas. Sempre que possível, enquadre a despesa em categoria específica. Despesas repetidas aqui podem indicar subnotificação ou má classificação.',
        obsEspecificas: 'O campo de especificação no SPCE deve ser preenchido com máximo de detalhe: natureza do gasto, finalidade eleitoral, beneficiário e contexto. Descrições genéricas como "serviços diversos" são insuficientes e podem gerar diligência.',
      },
    ],
  },
];

// Compatibilidade: lista plana para componentes existentes
export const gastos = generos.flatMap((g) => g.especies);
export type { Gasto };
